### ISSUE TITLE
Readme problems and vesrion update

### ISSUE THREAD

**Issue by paskal** [zabbix/zabbix-agent-chocolatey#10]
Hello!

First, README.md is crippled now (line break after first line is missing), and second - current version is 3.2.4, but repo have 3.2.0, it should be updated in my opinion.

**Comment by genebean** [comment]
In what way is the readme broken... it looks normal in my browser both from the repo's main page and from the file's page. As for the version, I'm happy to update just as soon as http://www.zabbix.com/download shows a newer pre-compiled version. As of right now the newest is 3.2.0. Thanks for helping us stay on top of things!

**Comment by paskal** [comment]
Readme is ok, I don't know where I was looking. Thank you!
