### ISSUE TITLE
new maintainers?

### ISSUE THREAD

**Issue by guilhem** [zabbix/zabbix-agent-chocolatey#12]
Anyone ready to help maintaining this project? :)

**Comment by KakersUK** [comment]
I don't mind helping to maintain this project. We use Zabbix and Chocolatey in our infrastructure.

**Comment by guilhem** [comment]
@KakersUK :tada:

**Comment by guilhem** [comment]
@KakersUK should be ok

**Comment by KakersUK** [comment]
Thanks!

**Comment by KakersUK** [comment]
@guilhem or @richlv is there any chance of getting more access to this repository? I'd like to be able to create branches to help support older versions still being released, such as "support/4.0".

**Comment by richlv** [comment]
@KakersUK, hmm, isn't that possible currently?

@guilhem, with you being the author of this project, I wouldn't want to override permissions without your approval, what's your take?

**Comment by KakersUK** [comment]
@richlv, Doesn't look like it. I get an 'Authentication failed' from the GitHub client when trying to push a new branch. I'll wait to see what guilhem comes back with :)

**Comment by guilhem** [comment]
@KakersUK you should be "Admin" now :)

**Comment by guilhem** [comment]
@richlv I grant you both full right / permission on this project ^^

**Comment by KakersUK** [comment]
Great, thanks @guilhem !
