### ISSUE TITLE
install path

### ISSUE THREAD

**Issue by l2aggron** [zabbix/zabbix-agent-chocolatey#13]
Please add possibility of change install/bin/conf paths via -ia parameters or something like this.
For example, we want to use this installation paths:
[custom_root_folder_name]
[custom_root_folder_name]\[custom_bin_folder_name]\*.exe
[custom_root_folder_name]\[custom_conf_folder_name]\[custom_conf_file_name].conf

**Comment by KakersUK** [comment]
Sounds like something which might be useful to people. I'll look at trying to get this added soon: before or if not inline with the upcoming 4.2.0 release.

**Comment by l2aggron** [comment]
It looks like the problem has been fixed, if I understand this line correctly in the [installation script](https://github.com/zabbix/zabbix-agent-chocolatey/blob/master/zabbix-agent.install/tools/chocolateyInstall.ps1):
`$INSTALLFOLDER        = if ($pp.INSTALLFOLDER) { $pp.INSTALLFOLDER } else { $installDir }`
