### ISSUE TITLE
Download URL is wrong

### ISSUE THREAD

**Issue by thefactor82** [zabbix/zabbix-agent-chocolatey#19]
ALL zabbix agent packages on chocolatey are not working anymore... I don't know what has changed, but the installer script tools\chocolateyInstall.ps1 has url to download:
"https://www.zabbix.com/downloads/$version/zabbix_agents-$version-win-amd64-openssl.zip"

do you see the portion: zabbix-agents ? (with the final S)
On the zabbix portal you can see that the url to download the file is without this final S... 
For example: https://www.zabbix.com/downloads/4.4.1/zabbix_agent-4.4.1-windows-i386.zip

**Comment by KakersUK** [comment]
This has been resolved by PR #18 I'll be trying to upload the packages to the chocolatey repos today, however the website doesn't seem to be playing ball..

**Comment by oharzallah-greenbull** [comment]
Any update on this ?

**Comment by KakersUK** [comment]
The chocolatey website still didn't allow for package updates, I've managed to push the packages via the choco push command to the respository.

It will take a few hours for their automated systems to check the package over and push to the CDN, once done it they will be available.
