### ISSUE TITLE
Error 404 when choco tries to install zabbix-agent 3.2.0

### ISSUE THREAD

**Issue by anmiles** [zabbix/zabbix-agent-chocolatey#20]
`ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.zabbix.com/downloads/3.2.0/zabbix_agents_3.2.0.win.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."`

I noticed that this page https://www.zabbix.com/download_agents#tab:32 have the only URL for downloading 3.2.0 agent for Windows: https://www.zabbix.com/downloads/3.2.0/zabbix_agent-3.2.0-windows-i386.zip

Probably URL format was changed on the Zabbix website this week. There were no any problems previous Friday. Ran into this just now.

**Comment by mpoirierj** [comment]
Similar to https://github.com/zabbix/zabbix-agent-chocolatey/issues/19. We're having the same thing using 3.4.6. 

Any plans to update for all versions?

**Comment by KakersUK** [comment]
I wasn't planning to based on the current life cycle and release policy: https://www.zabbix.com/life_cycle_and_release_policy.

However as these versions are still available for download from the website, I'll try and make them available via chocolatey hopefully today/tomorrow. This will encompass the 3.x and 2.x series, excluding 2.4 which is no longer available for download.

**Comment by KakersUK** [comment]
I've added the latest versions for each of the 3.x series where possible. Version numbering is a little different for 3.4.6 as it's the latest version already but we need to fix it.
 
Fix - 3.4.6.20200122
New - 3.2.7
New - 3.0.29
