### ISSUE TITLE
URL 404 for Zabbix Agent 5.2.0 and 5.0.6

### ISSUE THREAD

**Issue by JoeShabadu2000** [zabbix/zabbix-agent-chocolatey#24]
Saw an earlier ticket for Zabbix Server, but just FYI Zabbix Agent is also giving a 404 error.

Per the Zabbix website, it appears the 5.0.6 file download location is now:

https://cdn.zabbix.com/zabbix/binaries/stable/5.0/5.0.6/zabbix_agent-5.0.6-windows-amd64-openssl.zip

Based on the 404 error I receive in Chocolatey, it appears the installer is looking for:

https://www.zabbix.com/downloads/5.0.6/zabbix_agent-5.0.6-windows-amd64-openssl.zip

Thanks very much to the package maintainers for their work on these items!

**Comment by KakersUK** [comment]
Looks like the Zabbix team have moved over to using a CDN. I've updated the URLs for the future and manually pushed the new versions to the Chocolatey Repo. It'll take some time for the code verification on their part but should hopefully be resolved in a couple of hours.
