### ISSUE TITLE
URL 404 for Zabbix Agent 4.4.5

### ISSUE THREAD

**Issue by renatocmaia** [zabbix/zabbix-agent-chocolatey#26]
I am getting a 404 error for the choco install when attempting to download the package.

`The remote file either doesn't exist, is unauthorized, or is forbidden for URL 'https://www.zabbix.com/downloads/....`

I note on the website - it's now 4.4.5 and the URL looks to have changed, new URL is:

Zabbix agent v4.4.5 
DOWNLOAD   https://cdn.zabbix.com/zabbix/binaries/stable/4.4/4.4.5/zabbix_agent-4.4.5-windows-amd64-openssl.msi
DOWNLOAD   https://cdn.zabbix.com/zabbix/binaries/stable/4.4/4.4.10/zabbix_agent-4.4.10-windows-amd64-openssl.zip

**Comment by KakersUK** [comment]
Hi there,

Let me just prefrace this by saying although I work on this repo as a volunteer, outside that I don't have any affiliation with Zabbix so I don't have any insight to their internal workings.

Last year the Zabbix team did update the download URLs, which I found out about after the fact and had to go through and fix them. All of the package releases are done automatically as part of the AppVeyor configuration for Automatic Updates as recommended by Chocolatey.

If you check the listing for [zabbix-agent](https://chocolatey.org/packages/zabbix-agent) or [zabbix-agent.install](https://chocolatey.org/packages/zabbix-agent.install) you'll notice there are no versions listed for 4.2 and 4.4 as these are End Of Life as part of Zabbix's [Life Cycle & Release Policy](https://www.zabbix.com/life_cycle_and_release_policy).

The original release date for 4.4.5 was on 28 January 2020 and 4.4.10 was released on 29 June 2020. Now, I can appreciate these versions are still available on the Zabbix website to download, but it would be remiss of me to mention as this version is no longer supported, there will be no new versions being released including security updates (unless very severe). 

Currently there are no plans to manually add these versions and the better course of action would be to upgrade to 5.0, is this an option available to you at the moment?

**Comment by renatocmaia** [comment]
Hi @KakersUK,
Thank you for providing these clarifications.
My intention wasn't to mark you to fix this, If someone in the community didn't update to the new Zabbix version like me, so if the download was still available on the Zabbix website I think is are possible to fix it, helping other people.
But ok, I will follow your advice and update for the new version.

Regards.
