### ISSUE TITLE
Support Zabbix Agent 2

### ISSUE THREAD

**Issue by shane-davidson** [zabbix/zabbix-agent-chocolatey#27]
Can you guys please add support for zabbix-agent2

**Comment by SilmorSenedlen** [comment]
Good day
Is there any plans about adding support of zabbix-agent2?

**Comment by kristiantaylor** [comment]
defiantly interested too

**Comment by sahaqaa** [comment]
Hello, I am interested in this and wondering if this will be implemented? At least for Unix like OS's :-)

**Comment by mkevenaar** [comment]
Zabbix Agent 2 is available https://community.chocolatey.org/packages/zabbix-agent2
