### ISSUE TITLE
Packages not updating automatically

### ISSUE THREAD

**Issue by jberezanski** [zabbix/zabbix-agent-chocolatey#29]
The packages available on chocolatey.org are for version 5.4.3 ([zabbix-agent](https://community.chocolatey.org/packages/zabbix-agent#versionhistory), [zabbix-agent.install](https://community.chocolatey.org/packages/zabbix-agent.install#versionhistory)), yet the [latest available](https://www.zabbix.com/download_agents) agent version is now 5.4.7.

Although the packages have AU scripts and there exists an [AppVeyor pipeline](https://ci.appveyor.com/project/KakersUK/zabbix-agent-chocolatey), it seems that the pipeline is not set for scheduled runs and, as a consequence, the packages do not get automatically updated.

Could you please enable the automatic update flow? Thanks in advance!

**Comment by SilmorSenedlen** [comment]
Good day
Is there any news about package update?

**Comment by Hativ** [comment]
Any news on this?

We need a more recent version of 5.0 LTS because a bug has been fixed there.

**Comment by KakersUK** [comment]
Update checker was being blocked, this has been resolved. Also added in some new logic for the update script so it won't get any null errors.
