### ISSUE TITLE
Management of package

### ISSUE THREAD

**Issue by KakersUK** [zabbix/zabbix-agent-chocolatey#33]
I don't really have time to manage these packages anymore.
If anyone would like to help/take over management of the packages let me know.
Ideally you would need some experience with PowerShell, chocolatey and Automatic Package Updater.

**Comment by mkevenaar** [comment]
Hey,

I am a package maintainer of about 200 packages. I am willing to take over these packages.

Username mkevenaar on Chocolatey. 

Maurice

**Comment by KakersUK** [comment]
Hey Maurice,

Pretty extensive! That's great, thank you very much!
I'll get you set up with everything you need.

Jamie

**Comment by mkevenaar** [comment]
For ease of maintenance, these packages are now maintained here: https://github.com/mkevenaar/chocolatey-packages/
