### ISSUE TITLE
Chocolatey package not updated

### ISSUE THREAD

**Issue by genebean** [zabbix/zabbix-agent-chocolatey#8]
A couple of months ago you merged #7 yet the version at https://chocolatey.org/packages/zabbix-agent has not seen these changes... do you plan to push them and future ones? I as because, if not, I am going to publish one. If desired, I am also happy to help with this one. Thanks!

**Comment by paskal** [comment]
@genebean, your fork is nice, it will be cool to have it merged here.

@kYann, @guilhem, will it be possible? See [genebean/zabbix-agent-chocolatey](https://github.com/genebean/zabbix-agent-chocolatey) for commits and update notes.

**Comment by genebean** [comment]
@paskal - Thanks! FWIW, there is another PR open on mine right now that I am going to try and deal with tomorrow.

**Comment by genebean** [comment]
What are your plans for the Chocolatey package going forward? Are you planning on keeping it updated or having me keep running it out of my repo or what? I ask because, until now, this has basically been abandoned for more than two years now. The biggest thing for me is that we don't get into that boat again. 

Speaking of updating, I'm actually planning to update it to v3.x very soon. 

I look forward to working with you all on this!

**Comment by richlv** [comment]
@genebean, as nobody was working on it, i think it is appropriate for you to get permissions on it - any help highly appreciated :)

**Comment by genebean** [comment]
That sounds great to me @richlv, I am honored (seriously). Just as soon as I take care of [the open PR](https://github.com/genebean/zabbix-agent-chocolatey/pull/1) I'll start moving things over here. I look forward to working with you all on this!

**Comment by richlv** [comment]
you're very welcome - and thank you for your interest in zabbix :)

**Comment by genebean** [comment]
I just wanted to cross-post this from my fork so anyone looking here would see it too. "We are finally moving to Zabbix 3.2 at work which means I have some time to look at this (finally!). I will do my best to get this updated in the next few days and then pulled in upstream."

**Comment by genebean** [comment]
All updates merged and new packages submitted to chocolatey.org. Tags also applied to the repo to mark what packages were built off of.
